spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/frozenmeatsite_db
spring.datasource.username=postgres
spring.datasource.password=admin

# This line ensures Spring Boot doesn't accidentally delete or overwrite the tables your groupmate made
spring.jpa.hibernate.ddl-auto=none